@startuml
entity Boat {
    boat_id : BigInt
    boat_name : String
    typ_id : BigInt
    boat_isRented : boolean
}

entity Customer {
    customer_id : BigInt
    name : String
    address : String
    telephoneNumber : String
    email : String
}

entity Lease {
    lease_id : BigInt
    boot_id : BigInt
    customer_id : BigInt
    rental_begin : LocalDate
    rental_end : LocalDate
    price : double
}

entity Payment {
    payment_id : BigInt
    amount : double
    payment_date : LocalDate
    lease_id : BigInt
}

entity Employee {
    employee_id : BigInt
    name : String
    role : String
    telephoneNumber : String
}

entity Reservation {
    reservation_id : BigInt
    boat_id : BigInt
    customer_id : BigInt
    reservation_start_date : LocalDate
    reservation_end_date : LocalDate
}

entity BoatType {
    boatType_id : BigInt
    boat_name : String
}

entity Extras {
    extra : BigInt
    name : String
    description : String
    price : double
}

entity Yacht {
    yacht_id : BigInt
    name : String
    description : String
    price : double
    capacity : int
}

entity Sailboat {
    sailboat_id : BigInt
    name : String
    description : String
    price : double
    capacity : int
}

entity Motorboats {
    motorboat_id : BigInt
    name : String
    description : String
    price : double
    capacity : int
}


' Beziehungen

Customer -- "1..*" Reservation
Employee -- "1..*" Reservation

Reservation -- "1..*" Lease
Lease -- "1..1" Payment

Lease -- "1..*" Boat

Boat -- "*..1" BoatType
Boat -- "1..*" Extras




@enduml
