@startuml
entity Boat {
    boat_id : BigInteger
    name : String
    typ_id : BigInteger
    isRented : boolean
}

entity Customer {
    customer_id : BigInteger
    name : String
    address : String
    telephoneNumber : String
    email : String
}

entity Lease {
    lease_id : BigInteger
    boot_id : BigInteger
    customer_id : BigInteger
    rental_begin : LocalDate
    rental_end : LocalDate
    price : double
}

entity Payment {
    payment_id : BigInteger
    amount : double
    payment_date : LocalDate
    lease_id : BigInteger
}

entity Employee {
    employee_id : BigInteger
    name : String
    role : String
    telephoneNumber : String
}

entity Reservation {
    reservation_id : BigInteger
    boat_id : BigInteger
    customer_id : BigInteger
    reservation_start_date : LocalDate
    reservation_end_date : LocalDate
}

entity Extras {
    extra : BigInteger
    name : String
    description : String
    price : double
}

entity Yacht {
    yacht_id : BigInteger
    name : String
    description : String
    price : double
    capacity : int
}

entity Sailboat {
    sailboat_id : BigInteger
    name : String
    description : String
    price : double
    capacity : int
}

entity Motorboats {
    motorboat_id : BigInteger
    name : String
    description : String
    price : double
    capacity : int
}


' Beziehungen

Customer -- "1..*" Reservation
Employee -- "1..*" Reservation

Reservation -- "1..*" Lease
Lease -- "1..1" Payment

Lease -- "1..*" Boat

Boat -- "1..*" Extras

Boat <|-- Motorboats
Boat <|-- Sailboat
Boat <|-- Yacht


@enduml
